llm:
  type: deepseek
  models:
    openrouter: Null
    openai: Null
    anthropic: Null
    deepseek: "deepseek-chat"
  api_keys:
    openrouter: ""
    openai: ""
    anthropic: ""
    deepseek: "sk-0ab93c1f49df4306a8383c53911200b9"
  temperature: 0.7

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}.json"

